# Generated by Django 3.2.4 on 2021-06-17 14:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        CreateExtension('postgis'),

        migrations.CreateModel(
            name='BarberDetails',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('image', models.ImageField(upload_to='image/')),
                ('coords', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='coords')),
                ('location', models.CharField(max_length=1000)),
                ('about', models.TextField(blank=True)),
                ('contact', models.CharField(max_length=200)),
                ('employee_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('image', models.ImageField(upload_to='image/')),
                ('coords', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='coords')),
                ('location', models.CharField(max_length=1000)),
                ('about', models.TextField(blank=True)),
                ('contact', models.CharField(max_length=200)),
            ],
        ),
    ]
