# Generated by Django 3.2.2 on 2021-05-30 02:56

from django.contrib.postgres.operations import CreateExtension
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_alter_user_email'),
    ]

    operations = [
        # Create postgis extension on migrate
        CreateExtension('postgis'),

        migrations.CreateModel(
            name='BarberDetails',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('coords', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='coords')),
                ('location', models.CharField(max_length=200)),
                ('about', models.CharField(blank=True, max_length=1000)),
                ('website', models.URLField()),
                ('employee_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('coords', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='coords')),
                ('location', models.CharField(max_length=200)),
                ('about', models.CharField(blank=True, max_length=1000)),
                ('website', models.URLField()),
            ],
        ),
    ]
