# Generated by Django 3.2.4 on 2022-01-21 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.barberdetails')),
                ('business_name', models.CharField(max_length=100)),
                ('business_type', models.CharField(choices=[('individual', 'individual'), ('partnership', 'partnership'), ('proprietorship', 'proprietorship'), ('not_yet_registered', 'not_yet_registered')], max_length=100)),
                ('beneficiary_name', models.CharField(max_length=60)),
                ('account_number', models.PositiveBigIntegerField()),
                ('ifsc_code', models.CharField(max_length=20)),
                ('account_type', models.CharField(blank=True, choices=[('savings', 'savings'), ('current', 'current')], max_length=60, null=True)),
                ('account_id', models.CharField(max_length=60)),
                ('destination', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('barbershop', 'barbershop'), ('hair_salon', 'hair_salon'), ('beauty_salon', 'beauty_salon'), ('full_service_salon', 'full_service_salon'), ('other', 'other')], max_length=60)),
                ('service', models.CharField(max_length=100)),
                ('cost', models.PositiveIntegerField()),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.barberdetails')),
            ],
        ),
    ]
