# Generated by Django 3.2.2 on 2021-05-30 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20210530_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberdetails',
            name='about',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='barberdetails',
            name='employee_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='barberdetails',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='barberdetails',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='barberdetails',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='barberdetails',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='about',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
