# Generated by Django 3.2.4 on 2021-06-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210620_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordcodes',
            name='code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='signupcodes',
            name='code',
            field=models.CharField(max_length=15),
        ),
    ]
