# Generated by Django 3.2.4 on 2021-06-24 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210620_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberdetails',
            name='end_time',
            field=models.TimeField(default=datetime.time(20, 33, 55, 675536)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barberdetails',
            name='start_time',
            field=models.TimeField(default=datetime.time(20, 34, 1, 430862)),
            preserve_default=False,
        ),
    ]
