export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GET_ERRORS = "GET_ERRORS";

export const EMAIL_VERIFIED = "EMAIL_VERIFIED";
export const EMAIL_UNVERIFIED = "EMAIL_UNVERIFIED";
export const EMAIL_SENT = "EMAIL_SENT";

export const DETAIL_SUCCESS = "DETAIL_SUCCESS";
export const DETAIL_FAIL = "DETAIL_FAIL";
export const DETAIL_UPDATE_FAIL = "DETAIL_UPDATE_FAIL";

export const GET_BARBERS = "GET_BARBERS";

export const FIX_FAIL = "FIX_FAIL";

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const GET_APPOINTMENTS_FAIL = "GET_APPOINTMENTS_FAIL";

export const LOADING = "LOADING";
export const FETCHING = "FETCHING";

export const CHANGE_THEME = "CHANGE_THEME";
export const NEW_USER = "NEW_USER";

export const BANK_FAIL = "BANK_FAIL";
export const BANK_SUCCESS = "BANK_SUCCESS";

export const COMPELETION_FAIL = "COMPELETION_FAIL";
export const COMPELETION_SUCCESS = "COMPELETION_SUCCESS";

export const GET_SERVICES = "GET_SERVICES";
