# Generated by Django 3.2.4 on 2022-01-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircut', '0002_notificationtokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtokens',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
