# Generated by Django 3.2.4 on 2022-01-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircut', '0003_alter_notificationtokens_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtokens',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
