# Generated by Django 4.0.3 on 2022-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircut', '0005_appointments_bookingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='services',
            field=models.CharField(default='Haircuts', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='totalcost',
            field=models.PositiveIntegerField(default=199),
            preserve_default=False,
        ),
    ]
